org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mod_id=twilight_spark_delight
mod_name=Twilight Spark's Delight
mod_version=1.0.0
mod_license=CC BY-NC-SA 4.0
mod_group_id=xy177.twilightsparksdelight
