modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/xy177/Twilight-Spark-s-Delight/issues"

[[mixins]]
config="twilight_spark_delight.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/xy177/Twilight-Spark-s-Delight"
logoFile="logo_mini.png"
logoBlur=false
authors="xy177"
credits="FallenSnow21, L_CangS, thousvillages"
description='''
Twilight Spark's Delight / 暮光乐事
A Farmer's Delight-style food expansion for The Twilight Forest.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="farmersdelight"
type="required"
versionRange="[1.3.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="twilightforest"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
